#dev/prod

env: "dev"

mysql:
  host: "localhost"
  port: 3306
  username: "root"
  password: "password" 
  database: "my_database"
  max_open_conns: 20
  max_idle_conns: 10

redis:
  host: "localhost"
  port: 6379
  username: "root"
  password: "password"
  db: 0

server:
  port: "8080"
  mode: "debug"
  cors:
    allow_origins: ["http://localhost:3000", "http://127.0.0.1:3000"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allow_headers: ["Origin", "Content-Type", "Authorization"]
    allow_credentials: true