server:
  mode: "release"
mysql:
  max_open_conns: 50
  max_idle_conns: 20
upload:
  allowed_file_types: [".jpg", ".jpeg", ".png", ".gif", ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx", ".txt", ".zip", ".rar"]
