#dev environment

mysql:
  max_idle: 20  
  max_open: 50
redis:
  port: "6379"
  username: ""
  db: 0       
gin:
  mode: "debug"
  port: 8080
  cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]